title: Artistic Lifestyle photography
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6680851
  brandStrength: 1
  lightness: 0.5808511
  brandColors:
    - '#0D0502'
    - '#39312F'
    - '#D8A387'
    - '#665D5A'
    - '#928986'
  rhythmicContrast: 0.4510638
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: J. Monroe Studios
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8829787
layout_spectrum: 1
