name: J. Monroe Studios
favicon: null
layout_spectrum: 0.09372519934549928
typography_spectrum: 0.7135514367837459
title: Artistic Lifestyle photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#27abed'
    - '#080e0e'
    - '#fb0337'
    - '#155ca7'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
