name: J. Monroe Studios
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8829787
title: Artistic Lifestyle photography
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0D0502'
    - '#39312F'
    - '#D8A387'
    - '#665D5A'
    - '#928986'
  brandStrength: 0.875
  lightness: 0.5808511
  saturation: 0.6680851
  rhythmicContrast: 0.4510638
purpose: []
