title: Artistic Lifestyle photography
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3297491
  brandStrength: 1
  lightness: 0.6899642
  brandColors:
    - '#929395'
    - '#666769'
    - '#FFFFFF'
    - '#454648'
    - '#1C1C1C'
  rhythmicContrast: 0.265233
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: J. Monroe Studios
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8960574
layout_spectrum: 0.3727598
